# config/packages/security.yaml
security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      form_login:
        login_path: app_login
        check_path: app_login
        failure_path: app_login
        enable_csrf: true
        username_parameter: _username
        password_parameter: _password
        always_use_default_target_path: false
        use_referer: true
        default_target_path: app_dashboard
      logout:
        path: app_logout
        target: app_home
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 1209600   # 14 jours
        path: /

  access_control:
    #- { path: ^/login, roles: PUBLIC_ACCESS }